<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Executing testA]]>
    </line>
    <line>
      <![CDATA[Test:testA is Fail]]>
    </line>
    <line>
      <![CDATA[TestName:testA Status:FAIL]]>
    </line>
    <line>
      <![CDATA[PHOTO:./photo/Wed Oct 03 09_27_26 IST 2018.png]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="5787" started-at="2018-10-03T03:57:21Z" finished-at="2018-10-03T03:57:27Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5787" started-at="2018-10-03T03:57:21Z" finished-at="2018-10-03T03:57:27Z">
      <class name="script.DemoA">
        <test-method status="PASS" signature="openApp(java.lang.String, java.lang.String)[pri:0, instance:script.DemoA@2a5ca609]" name="openApp" is-config="true" duration-ms="4795" started-at="2018-10-03T09:27:21Z" finished-at="2018-10-03T09:27:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[localhost]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method status="FAIL" signature="testA()[pri:0, instance:script.DemoA@2a5ca609]" name="testA" duration-ms="5" started-at="2018-10-03T09:27:26Z" finished-at="2018-10-03T09:27:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at script.DemoA.testA(DemoA.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Executing testA]]>
            </line>
            <line>
              <![CDATA[Test:testA is Fail]]>
            </line>
          </reporter-output>
        </test-method> <!-- testA -->
        <test-method status="PASS" signature="closeApp(org.testng.ITestResult)[pri:0, instance:script.DemoA@2a5ca609]" name="closeApp" is-config="true" duration-ms="971" started-at="2018-10-03T09:27:26Z" finished-at="2018-10-03T09:27:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testA status=FAILURE method=DemoA.testA()[pri:0, instance:script.DemoA@2a5ca609] output=Executing testA]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[TestName:testA Status:FAIL]]>
            </line>
            <line>
              <![CDATA[PHOTO:./photo/Wed Oct 03 09_27_26 IST 2018.png]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- script.DemoA -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
